#pragma once

#include <sqt/orm/utility/macro_utility.h>

#define SQT_MAKE_INDEX_BASE_TYPE_NAME(NAME) IndexBaseType_##NAME 
#define SQT_INDEX_BASE_TYPE_NAME_(NAME) SQT_MAKE_INDEX_BASE_TYPE_NAME(NAME)
#define SQT_INDEX_BASE_TYPE_NAME(...) SQT_INDEX_BASE_TYPE_NAME_(SQL_UTILITY_JOIN(__VA_ARGS__))

#define SQT_MAKE_INDEX_TYPE_NAME(NAME) IndexType_##NAME 
#define SQT_INDEX_TYPE_NAME_(NAME) SQT_MAKE_INDEX_TYPE_NAME(NAME)
#define SQT_INDEX_TYPE_NAME(...) SQT_INDEX_TYPE_NAME_(SQL_UTILITY_JOIN(__VA_ARGS__))

#define SQT_MAKE_INDEX_NAME(NAME) Index_##NAME 
#define SQT_INDEX_NAME_(NAME) SQT_MAKE_INDEX_NAME(NAME)
#define SQT_INDEX_NAME(...) SQT_INDEX_NAME_(SQL_UTILITY_JOIN(__VA_ARGS__))